### ISSUE TITLE
Doesn't activate

### ISSUE THREAD

**Issue by aahoogendoorn** [benbalter/wordpress-to-jekyll-exporter#101]
When activating the plug-in in my Worpress, it gives the following parse error: **syntax error, unexpected '|', expecting ')'** in **/public_html/wp-content/plugins/jekyll-exporter/jekyll-exporter.php on line 426**. Any ideas?

**Comment by ynagorny** [comment]
I got the same error when activating it.

**Comment by benbalter** [comment]
@ynagorny @aahoogendoorn what version of PHP are you running?

**Comment by aahoogendoorn** [comment]
It's my blog, which is running on WordPress 4.8.1. Not sure which PHP version it is.

**Comment by benbalter** [comment]
Does the problem continue if you upgrade to version 2.2.2?

**Comment by aahoogendoorn** [comment]
Done, plugin is now activated.. Thanks.
