### ISSUE TITLE
Syntax highlighting is lost during conversions

### ISSUE THREAD

**Issue by ohadschn** [benbalter/wordpress-to-jekyll-exporter#106]
Examples:
1. PowerShell - [source](https://www.ohadsoft.com/2016/04/invoking-arbitrary-powershell-commands-with-retries-in-powershell/), [taget](https://github.com/ohadschn/ohadschn.github.io/blob/github/_posts/2016-04-17-invoking-arbitrary-powershell-commands-with-retries-in-powershell.md) 
1. XML - [source](https://www.ohadsoft.com/2016/04/redirecting-all-urls-to-their-https-www-equivalents/), [target](https://github.com/ohadschn/ohadschn.github.io/blob/github/_posts/2016-04-02-redirecting-all-urls-to-their-https-www-equivalents.md)

It looks like XML characters, specifically `<`> and `>`, trip it up.

**Comment by benbalter** [comment]
Ahh, so it looks like we need to *not* XML escape `<` and `>`s when they're in a code block? I believe [Markdownify](https://github.com/Elephant418/Markdownify) is what's doing the escaping and may not be code-block-aware.

**Comment by ohadschn** [comment]
The problem is that code blocks stay as `<pre>` (and/or possible `<code>`), rather than get converted to markdown code blocks (with back ticks). 

Ideally something like `<pre class="brush: powershell">foo</pre>` would be converted to:
```` 
```powershell 
foo
```
````
