### ISSUE TITLE
Export drafts

### ISSUE THREAD

**Issue by ohadschn** [benbalter/wordpress-to-jekyll-exporter#107]
As requested here: https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/85. 

Couldn't the same logic used for posts (except outputting to [`_drafts`](https://jekyllrb.com/docs/drafts/) ) be applied here for a quick win?

**Comment by benbalter** [comment]
> Couldn't the same logic used for posts (except outputting to _drafts ) be applied here for a quick win?

Yep. 👍. Added the `help-wanted` label in case you (or anyone) is interested in adding this feature.

**Comment by ohadschn** [comment]
So basically:

1. Remove the `post_status` filter here: https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/aee948313f9a1a422f70a42bc5fe3b4d73a94226/jekyll-exporter.php#L138
2. Check `get_post_status` here and put _publish_ in `_posts` (or post URI filename in case of pages) and everything else in `_drafts`: https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/aee948313f9a1a422f70a42bc5fe3b4d73a94226/jekyll-exporter.php#L399

Sounds about right?

**Comment by benbalter** [comment]
@ohadschn Yes! That sounds right, with one note, per the docs [drafts don't have dates](https://jekyllrb.com/docs/drafts/).

**Comment by benbalter** [comment]
Implemented via #108.
