### ISSUE TITLE
can't activate the plugin

### ISSUE THREAD

**Issue by utkusen** [benbalter/wordpress-to-jekyll-exporter#110]
Hello,

My wordpress version: 4.8.2
Plugin version: 2.2.3

When I try to activate the plugin, I got following error:

`Parse error: syntax error, unexpected T_STRING in /home/........../wp-content/plugins/wordpress-to-jekyll-exporter/jekyll-exporter.php on line 254`

Any suggestion?

**Comment by benbalter** [comment]
@utkusen Please see https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/master/docs/required-php-version.md. I believe you will need to upgrade the version of PHP you are using.
