### ISSUE TITLE
Code blocks might need indentation

### ISSUE THREAD

**Issue by chmac** [benbalter/wordpress-to-jekyll-exporter#114]
I think my existing issue #113 is slightly different.

I realised that on GitHub, rendering a block of code with a single leading and trailing backticks does not render newlines inside the code block. The code must be wrapped in either three backticks, or indented 4 spaces.

In my expert, I have some code blocks where the `<code>` and `</code>` tags was converted to single back ticks.

Maybe this is an issue that should be posted on [Markdownify](https://github.com/Elephant418/Markdownify)?

Here's a few examples:

```
code
two
```

    one
    two

`one
two`

**Comment by benbalter** [comment]
> a block of code with a single leading and trailing backticks does not render newlines inside the code block. The code must be wrapped in either three backticks, or indented 4 spaces.

That is the expected markdown behavior. Single backticks is inline code, three backticks is a code block.

> In my expert, I have some code blocks where the <code> and </code> tags was converted to single back ticks.
> 
> Maybe this is an issue that should be posted on Markdownify?

I believe so, yes.

**Comment by chmac** [comment]
Gotcha. Thanks. Reported it there, will close this issue here.
