### ISSUE TITLE
Fail to create .zip file

### ISSUE THREAD

**Issue by claudiuconstantin** [benbalter/wordpress-to-jekyll-exporter#116]
The default "Export to Jekyll" menu doesn't work, it rather blocks my disk size by creating a huge amount of trash data. I tried to run the command-line utility and it creates an invalid .zip file that cannot be open. Is there a way to make this work? 

I am running WordPress 4.9.4 , PHP v5.6.34

**Comment by BenjaminLawson** [comment]
This is a known bug, with a workaround available in #70 .

**Comment by BenjaminLawson** [comment]
#70 isn't a real fix, it just takes advantage of the fact that the export is temporarily stored in /tmp/ before being zipped. What I think is happening is that websites on shared hosting are hitting a memory or time limit constraint when zipping the directory in the zip_folder function. The same website that had this issue on shared hosting worked fine when hosted on my computer.

**Comment by BenjaminLawson** [comment]
When the export results in a 500 error, the cause is the PHP [max_execution_time](http://php.net/manual/en/info.configuration.php#ini.max-execution-time) being set too low, but I think the corrupt zip files are caused by this error:

> [27-Mar-2018 20:41:20 UTC] PHP Warning:  copy(/tmp/wp-jekyll-cb1507c39127b6e398b7f292c0869abe/wp-content/uploads/2014/11/example.jpg): failed to open stream: No such file or directory in /home/.../wp-admin/includes/class-wp-filesystem-direct.php on line 243
> [27-Mar-2018 20:41:20 UTC] PHP Warning:  ZipArchive::close(): Seek error: No space left on device in /home/.../wp-content/plugins/jekyll-exporter/jekyll-exporter.php on line 448
