### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in ...

### ISSUE THREAD

**Issue by prokoudine** [benbalter/wordpress-to-jekyll-exporter#131]
### Describe the bug

HTTP 500 error code when visiting hostname/wp-admin/export.php?type=jekyll.

### Steps to reproduce the behavior

1. Install and activate the plug-in
2. Go to hostname/wp-admin/export.php?type=jekyll
3. HTTP ERROR 500

### Expected behavior

Some sort of UI for exporting to Jekyll should open up, I expect?

### Screenshots

It's the standard HTTP 500 error message in Chrome :)

### Additional context

Can't think of any.

**Comment by benbalter** [comment]
Are you able to access the specific error, either via your logs or possibly via `WP_DEBUG`?

**Comment by vertoforce** [comment]
Same issue here.  This is the error:
```
PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in .../plugins/jekyll-exporter/jekyll-exporter.php
```

**Comment by benbalter** [comment]
See https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/36 and https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/98#issuecomment-326171444. You will need to activate the Zip extension in your `php.ini` file.
