### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by erwinbierens** [benbalter/wordpress-to-jekyll-exporter#144]
When i try to run the command by ssh i'm getting this error back every time.. 
i dont see anything in the logs.

PHP Fatal error:  Cannot redeclare get_file_description() (previously declared in /var/www/vhosts/erwinbierens.com/httpdocs/wp-admin/includes/file.php:78) in /var/www/vhosts/erwinbierens.com/httpdocs/wp-admin/includes/file.php on line 94

**Comment by erwinbierens** [comment]
In debug i see the following error:
Uninitialized string offset: 0
 Type: PHP Notice Line: 929
 File: /var/www/vhosts/domainname/httpdocs/wp-content/plugins/wordpress-to-jekyll-exporter-master/vendor/pixel418/markdownify/src/Converter.php

**Comment by benbalter** [comment]
Do you know if you have another plugin that depends on markdownify?

**Comment by paragjnath** [comment]
I have had this issue too when I installed this plugin after installing 'WordPress2Jekyll' plugin. I was able get my site running again after deleting html/wp-content/plugins/jekyll-exporter folder manually.

When I installed this plugin again after removing 'WordPress2Jekyll' plugin this plugin worked perfectly.
