### ISSUE TITLE
Timeout - Any way to do the export in a background thread?

### ISSUE THREAD

**Issue by ardalis** [benbalter/wordpress-to-jekyll-exporter#195]
### Describe the bug

I get a gateway timeout error when I export. I have about 1500 posts.

### Steps to reproduce the behavior

1. Go to 'Tools'
2. Click on 'Export to Jekyll'

### Expected behavior

A download of markdown files in a zip file.

### Screenshots

![image](https://user-images.githubusercontent.com/782127/79929643-50523a80-8414-11ea-970f-845d7b554bbd.png)

**Comment by jjegg** [comment]
also experiencing this problem.

**Comment by jjegg** [comment]
I think we might need to run it locally to export it fully. For example https://www.davidebarranca.com/2019/03/migrating-from-wordpress-to-jekyll-on-netlify/#wordpress-migration

**Comment by ardalis** [comment]
Locally on the shared server in prod? Not an option.

Locally on my dev machine? I'm trying but so far haven't figured out how to do so.

**Comment by jonny-wg2** [comment]
yeah so it's best to backup your Wordpress from prod and then run it locally and then use the plugin. I have the same issue where my hosting provider is blocking the download generating as it's a lot of files and pictures.

**Comment by ardalis** [comment]
What's your recommendation on how best to restore and run a Wordpress site backup on Windows 10?
