### ISSUE TITLE
youtube links completely stripped out of results

### ISSUE THREAD

**Issue by clolsonus** [benbalter/wordpress-to-jekyll-exporter#222]
### Describe the bug

I have a wordpress blog that includes posts with youtube links.  When I export my blog to jekyll, all these links are completely stripped out and gone.  I could do some manual repair, but I have a ton of blog posts going back 10 years and if the youtube links are silently stripped out, it's difficult to even know they are gone.  Is there a solution, or work around, or way to deal with this?  Even if it's just a local mod/edit I can make on my side (I have shell access to my wordpress host.)  Is there a way to let the youtube links pass through to the final markdown so I can at least go through my converted jekyll posts (markdown) and find/fix them manually here?

### Steps to reproduce the behavior

1. export your wordpress site to jekyll
2. youtube links are completely missing (stripped) from post markdown

### Expected behavior

I realize that default jekyll doesn't have clean way to deal with youtube links, but all I want is for those links to carry through to the post markdown so I can repair things locally.

### Screenshots

n/a

### Additional context

I saw a similar issue reported here a while back, but it got marked as stale/won't fix ... but with no explanation why it won't be fixed.  Just looking for a path forward that doesn't amount to having to look through each wp blog post, compare to each jekyll post, find missing pieces and copy them over manually ... thanks!

**Comment by clolsonus** [comment]
For whatever it's worth, I went through my posts manually on the original wordpress site and found all the instances of youtube.com and youtu.be and migrated all those over to jekyll/markdown manually.  Not the ideal situation, but I guess I'm only doing it once and now it's done.  So maybe some way to address this for others in the future would nice?  Maybe I'm the last one to convert from wordpress to jekyll?  For me, please feel free to close this issue and we can move forward to more interesting things.  Perhaps if someone has a better strategy for manually finding/fixing/migrating these, they could chime in so the next person at least has a work around or an idea to start with.  Anyway, thanks so much for the plugin.  Overwhelmingly it did a solid job.  My blog is now running under 100% jekyll and I really like how zippy and clean the pages are.  Thanks!

**Comment by deirdresm** [comment]
Can confirm that this happened to me as well. In my case, it is enclosed in a wp:core-embed/youtube block in a <content:encoded> tag. I've added the exported code from a post in this gist:

https://gist.github.com/deirdresm/337782ccb6aecd2080d42e0d44b92703

**Comment by benbalter** [comment]
I believe this should be fixed with the latest version, version 2.3.3.
