### ISSUE TITLE
Question: Timeout

### ISSUE THREAD

**Issue by lukefretwell** [benbalter/wordpress-to-jekyll-exporter#242]
@benbalter!

I'd like to move GovFresh from WordPress to Jekyll. When I use the plugin, I get a request time-out error. I've upped the time-out time, but that doesn't seem to work.

Does this mean GovFresh is probably too 'heavy' for this plugin?

**Comment by benbalter** [comment]
Check out the [command-line instructions](https://ben.balter.com/wordpress-to-jekyll-exporter/command-line-usage/) which should allow you to bypass the timeout.

**Comment by lukefretwell** [comment]
Thank you @benbalter. Will look into it. 

I did use it to move all of the CityCamp blog posts and website to Jekyll/GitHub: http://citycamp.com/

What I need to deep-dive on is how to easily attach the images to the posts md files.
