### ISSUE TITLE
Uncaught Error: Class "ZipArchive" not found

### ISSUE THREAD

**Issue by seanthegeek** [benbalter/wordpress-to-jekyll-exporter#319]
WordPress version 6.6.1
Active theme: GeneratePress (version 3.4.0)
Current plugin: WordPress to Jekyll Exporter (version 2.4.0)
PHP version 8.2.20

> An error of type E_ERROR was caused in line 420 of the file /var/www/seanthegeek.net/wp-content/plugins/jekyll-exporter/jekyll-exporter.php. Error message: Uncaught Error: Class "ZipArchive" not found in /var/www/seanthegeek.net/wp-content/plugins/jekyll-exporter/jekyll-exporter.php:420

I can't test a fix because I've already migrated my blog by other means.

**Comment by benbalter** [comment]
For others that land here, see https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/36 and https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/98#issuecomment-326171444. You will need to activate the Zip extension in your `php.ini` file.
