### ISSUE TITLE
Using the the_content filter outside "the loop" causes bugs

### ISSUE THREAD

**Issue by kevinpapst** [benbalter/wordpress-to-jekyll-exporter#322]
### Describe the bug

I ran into really weird export issues, as my configured post_types were seemingly ignored. I am missing many pages, getting unexpected and others land in completely wrong directories (e.g. `pages` in `_attachments/`).

After a longer debugging session I found out it is caused by `apply_filters( 'the_content', $post->post_content );` in [line 249](https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/master/jekyll-exporter.php#L249):

As the docs say: https://developer.wordpress.org/reference/hooks/the_content/

> When using this filter it’s important to check if you’re filtering the content in the main query with the conditionals [is_main_query()](https://developer.wordpress.org/reference/functions/is_main_query/) and [in_the_loop()](https://developer.wordpress.org/reference/functions/in_the_loop/)... Without these conditionals you could unintentionally be filtering the content for custom loops in sidebars, footers, or elsewhere.

This means, all plugins adding their callbacks expect that the `global $post` contains the current page. 

But your are using custom logic to fetch and iterate the posts, so some plugins run wild and completely mess with the IDs.

When I add a `var_dump` like that around [line 290](https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/master/jekyll-exporter.php#L290)

```php
var_dump($post_id, get_post_type($post));
$output .= $this->convert_content( $post );
var_dump($post->ID, get_post_type($post));echo PHP_EOL;
```
I can see that something changes the $post object unexpected:

```bash
string(2) "45"
string(4) "page"
int(49)
string(10) "attachment"

string(3) "255"
string(4) "page"
int(296)
string(11) "sprungplatz"

string(4) "1555"
string(4) "page"
int(1580)
string(7) "lexikon"

string(4) "1697"
string(4) "page"
int(300)
string(11) "sprungplatz"
```

</details>

The fix that is working for me is to replace these lines:
```php
// $content = apply_filters( 'the_content', $post->post_content );
$content = get_the_content(null, false, $post);
```

I didn't want to send a PR before discussion, because you have way more experience with migrations than I do.

Edit: the main difference is that `get_the_content()` does not execute shortcodes ... which in my situation is better anyway, so I can build includes (or Jekyll plugins) for these parts. 
Yes, I understand that this is a case-for-case decision, but the current logic just breaks my entire export and I am not doing something super fancy, just using the wildly popular "Advanced custom fields" plugin with a few custom content types.

**Comment by benbalter** [comment]
Thanks for digging into this @kevinpapst. I agree that `get_the_content` is the "better" way to go, and we can document the shortcode functionality. I agree, personally I'd rather change the shortcode to a Jekyll tag than commit the rendered output.

**Comment by kevinpapst** [comment]
Okay, I can prepare a PR later to change that and add some sentences to the docs to explain that people have to handle the shortcodes manually in a later step.
