### ISSUE TITLE
Blank page on Wordpress 4.01

### ISSUE THREAD

**Issue by jonclemons** [benbalter/wordpress-to-jekyll-exporter#47]
I've deleted all plugins and before trying and and only see a blank page.
host: wpengine
plugin version: 2.01

**Comment by benbalter** [comment]
What version of PHP are you running?

**Comment by kwilson** [comment]
Blank page here as well. Tested with PHP 5.4 and 5.5. Same result in both.

Hosting on Azure Websites if that's of any use. Everything is up-to-date.

**Comment by benbalter** [comment]
Could you clarify when you see the blank page? Activation? Export?

Also, is it possible to retrieve the error log (either via your hosting environment, or by activating `WP_DEBUG` which should show the error itself.

**Comment by kwilson** [comment]
The plugin activates okay. After I click to do the export (/blog/wp-admin/export.php?type=jekyll) there's around a 30 second delay waiting for a response then I just get a blank page with a 500 response.

Here's the extract from the log file:

	[28-Jan-2015 00:57:32 UTC] PHP Fatal error:  Uncaught exception 'Alchemy\Zippy\Exception\InvalidArgumentException' with message 'The stream or file "C:\DWASFiles\Sites\kwilsonmeuk\Temp/wp-jekyll-18e0e170f978ea01d0d9b98c61ba932c/" could not be opened: ' in D:\home\site\wwwroot\blog\wp-content\plugins\jekyll-exporter\vendor\alchemy\zippy\src\Alchemy\Zippy\Resource\Teleporter\StreamTeleporter.php:35
	Stack trace:
	#0 D:\home\site\wwwroot\blog\wp-content\plugins\jekyll-exporter\vendor\alchemy\zippy\src\Alchemy\Zippy\Resource\ResourceTeleporter.php(41): Alchemy\Zippy\Resource\Teleporter\StreamTeleporter->teleport(Object(Alchemy\Zippy\Resource\Resource), 'C:\\DWASFiles\\Si...')
	#1 D:\home\site\wwwroot\blog\wp-content\plugins\jekyll-exporter\vendor\alchemy\zippy\src\Alchemy\Zippy\Resource\ResourceManager.php(67): Alchemy\Zippy\Resource\ResourceTeleporter->teleport('C:\\DWASFiles\\Si...', Object(Alchemy\Zippy\Resource\Resource))
	#2 D:\home\site\wwwroot\blog\wp-content\plugins\jekyll-exporter\vendor\alchemy\zippy\src\Alchemy\Zippy\Adapter\ZipExtensionAdapter.php(2 in D:\home\site\wwwroot\blog\wp-content\plugins\jekyll-exporter\vendor\alchemy\zippy\src\Alchemy\Zippy\Zippy.php on line 63

**Comment by kerim** [comment]
I'm having this problem too, on 4.1.1.

**Comment by kerim** [comment]
This might help. I tried to run the plugin from the command line and got a similar error to what @kwilson saw:

`PHP Fatal error:  Class 'ZipArchive' not found in /users/home/kerim/domains/keywords.oxus.net/web/public/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/ZipExtensionAdapter.php on line 208`

**Comment by kerim** [comment]
I've asked my system admin to add this (ZipArchive) to my PHP, but I'm wondering if there is any alternative, in case that can't be done?

**Comment by kerim** [comment]
OK. He fixed it. I was able to run the plugin from the command line without an error. However I still get a 500 server error trying to load the plugin from the dashboard.

**Comment by drewbots** [comment]
Deactivating all other plug-ins was the trick for me. Thanks for mentioning that.

**Comment by lucaciavatta** [comment]
WP 4.3, PHP 5.4.41, plug-in activation is ok.
When I click 'Export to Jekyll' there's around a 30 second / 2 minutes delay waiting for a response then I just get a 'Page not found' error 404 response.

**Comment by ogbaoghene** [comment]
Please, any fix for this? Deactivating other plugins didn't work for me.

**Comment by evandegr** [comment]
I get the same  'Page not found'  error

**Comment by ogbaoghene** [comment]
Running it locally worked fine for me.

**Comment by jcortell** [comment]
I get the same error.

**Comment by csethna** [comment]
Hey @benbalter thank you SO much for making this. It seems to be the go-to solution for migrating wordpress sites to Jekyll.

I am getting the 500 Internal Server Error and I'm not able to find a workable solution. I tried mucking with the other plugins I have installed per the discussion in this thread, but what can I do to resolve this error?

Thanks in advance for your consideration.

**Comment by fuzzy76** [comment]
FWIW, 500 Internal Server Error could be _anything_, and not necessarily the same issue as this. You need to get the logs from the server with the full error message.

**Comment by benbalter** [comment]
Googling suggests it should be a header problem, but looking at https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/1efa5d4f7778ae94f6ab782dc84af9215ff0f4db/jekyll-exporter.php#L466-L468, we're setting the appropriate headers... any ideas?

**Comment by fuzzy76** [comment]
As far as I can tell, the Firefox message suggests your TLS/HTTPS setup is wrong, and should not have anything to do with this plugin.

As for the Chrome messages, there are some solutions here.... https://stackoverflow.com/questions/6587393/resource-interpreted-as-document-but-transferred-with-mime-type-application-zip

**Comment by jkchilds** [comment]
@benbalter would you be willing to let anyone push up a potential fix?
