### ISSUE TITLE
not working with WordPress 4.1

### ISSUE THREAD

**Issue by pkozelka** [benbalter/wordpress-to-jekyll-exporter#48]
fails with this message:

> Plugin could not be activated because it triggered a **fatal error**.

**Comment by benbalter** [comment]
Do you have any sense of what the error is? Is the error the same with WP_DEBUG activated? What version of PHP are you using?

**Comment by olimart** [comment]
Hi @benbalter I just installed but it failed to activate due to fatal error (wp 3.6.1, PHP 5.2.17)

```
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /.../wp-content/plugins/jekyll-exporter/jekyll-exporter.php on line 27
```

**Comment by NSmeef** [comment]
I also get this.

**Comment by benbalter** [comment]
@olimart @NSmeef what version of PHP are you using?

**Comment by benbalter** [comment]
Ahh. Just saw @olimart noted they were using 5.2. Per https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/40#issuecomment-67016093:

> PHP 5.2 lost support from the PHP project itself more than three years ago. You'll need to be running at least PHP 5.3 which adds namespace support (the reason it's breaking), but I'd recommend at least 5.4 (or the latest your host supports) as it's the oldest supported version: https://en.wikipedia.org/wiki/PHP#Release_history

**Comment by olimart** [comment]
Thanks @benbalter 
3 years ago!!! what is my host waiting for to upgrade??? (but that's a different issue). I did find a solution so all good. thanks.

**Comment by benbalter** [comment]
You may be able to choose a different version via your account management console if you are on a shared host.
