### ISSUE TITLE
Repeated warnings and fatal error

### ISSUE THREAD

**Issue by frankchen07** [benbalter/wordpress-to-jekyll-exporter#49]
Hello,

Thanks for writing and supporting this plugin.

I'm having some difficulty getting past some errors. I'm running **Wordpress 4.1**, **PHP 5.4**, and the latest version of the **wordpress exporter**.

I'm receiving multiples of this type of error: 

**Warning: copy(/tmp/wp-jekyll-d90dca3e9ec4c36e485e8704959d9be1/wp-content/uploads/2012/09/052912-le-trumilou-2-courtesy-jc1-700x525.jpg): failed to open stream: No such file or directory in /home2/knarf/public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 231**

finished with a: 

**Fatal error: Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'Failed to create "/tmp/zippy_54c5176d46489": mkdir(): No space left on device.' in /home2/knarf/public_html/......** (shortened)

Any help would be greatly appreciated. Please let me know if there is any additional information you may need.

**Comment by benbalter** [comment]
> `No space left on device.`

Is it possible you've run out of space? You'd likely need *double* the space used by your site, uploads included.

**Comment by frankchen07** [comment]
I've contacted **HostGator** and they've confirmed that I am not out of diskspace (they apparently don't limit diskspace), and suggested that it was a **"scripting error."**

I did notice that the repeated **Warning: copy(/tmp/wp-jekyll-....** errors are all **.jpgs**...is there something about images that breaks the export?

**Comment by bbBobbyEarl** [comment]
I'm on Dreamhost shared service and can confirm the same problem.  Similar warnings and eventual fatal error.  Associated with an installation that has large image attachments.  It does appear to be because of space limits on the "/tmp/" folder.

**Comment by benbalter** [comment]
Does it sounds like using someplace in `wp-content` as the scratch dir will resolve the issue?

**Comment by bbBobbyEarl** [comment]
I do believe that would solve the problem.

**Comment by hishnband** [comment]
Hi, I get  similar fatal error, but on line 27.

> Plugin could not be activated because it triggered a fatal error.
>
> Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /mounted-storage/.../wordpress/wp-content/plugins/jekyll-exporter/jekyll-exporter.php on line 27

I'm using WP 4.2.3 on PHP  5.2.42. If anyone has an idea how to solve this, I'd be more than grateful.

**Comment by lucaciavatta** [comment]
Hi,
I get exactly the same fatal error on line 27.
I have cleaned the cache and unactivated many plug-ins, but nothing.

**Comment by lucaciavatta** [comment]
I deleted the plug-in installed directly from WP and I have loaded this master.
I get the same error but on line 32, so the problem is:
'''
use Alchemy\Zippy\Zippy;
'''
I have PHP 5.4.41. Any idea?

**Comment by lucaciavatta** [comment]
I have update to PHP 5.4.41 and all goes well. Thx for this plug-in.

**Comment by InsidiousMind** [comment]
Im on 1&1, same error

**Comment by benbalter** [comment]
> I do believe that would solve the problem.

You should be able to explicitly specify that the plugin to use a folder within wp-content by adding the following to your site's config:

```php
define( 'WP_TEMP_DIR', '/path-to-wp-content/');
```
