### ISSUE TITLE
Exporter loses iframes

### ISSUE THREAD

**Issue by prokoudine** [benbalter/wordpress-to-jekyll-exporter#52]
I've a bunch of <iframe> tags with youtube and vimeo videos. They are all lost in exported .md files. How can I work around that?

**Comment by benbalter** [comment]
I suspect it's going to be a matter of passing the appropriate argument to [markdownify](https://github.com/benbalter/wordpress-to-jekyll-exporter/tree/master/vendor/pixel418/markdownify) to teach it to pass (not drop) unknown tags.

**Comment by sumdog** [comment]
I encountered this same issue. There's a list of unsafe tags in markdownify that get dropped. It's not an option you can turn off via property or constructor argument unfortunately. A quick hack is to go into `vendor/pixel418/markdownify/src` in the plugin directory and edit `Markdownify/Converter.php`.

Comment out the following line:

    $this->parser->html = preg_replace('#<(' . implode('|', $this->drop) . ')[^>]*>.*</\\1>#sU', '', $this->parser->html);

It's line 316 in my source. Actually patching this the right way for the plugin will be difficult. It would require either a fork or upstream patch to markdownify. If we had those, there could be an option for wordpress-to-jekyll-exporter for _unsafe html_ exports.

**Comment by benbalter** [comment]
Sounds like @sumdog's solution is the best for now, unless someone would like to open an issue upstream with Markdownify.
