### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by wnowicki** [benbalter/wordpress-to-jekyll-exporter#53]
Hi,

I'm getting issue while trying to activate plugin

*Plugin could not be activated because it triggered a fatal error.*
```PHP
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /[...]/wp-content/plugins/jekyll-exporter/jekyll-exporter.php on line 27
```

**Comment by benbalter** [comment]
Please see https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/40#issuecomment-67016093. You'll need to update your PHP version.
