### ISSUE TITLE
Empty wp-content

### ISSUE THREAD

**Issue by elbaulp** [benbalter/wordpress-to-jekyll-exporter#54]
Hi, I am trying to export all my post, pages and uploads to jekyll but with no luck. The wp-content directory is empty. 

I've tried with both `wp-cli` and `php jekyll-export-cli.php > jekyll-export.zip`. As I have a custom wordpress structure, I thought that wp-cli will solve the problem, but it didn't.

The first error that I've encounter with wp-cli was that it can not find `jekyll-export` as a command. So I downloaded the plugin to `~/.wp-cli` as explained here https://github.com/wp-cli/wp-cli/wiki/Community-Packages

After that, the plugin was able to run, but with errors like:

```
PHP Fatal error: Cannot redeclare cli\render() 
```

After commenting all the function redeclared, I keep getting things like:

```
Cannot redeclare class Spyc in
```

I do not know what more I can do to be able to download the contents of wp-content.

Is worth mentioning that I have a custom wordpress structure, like this:

```
.
├── content
├── index.php
├── robots.txt
├── wordpress
└── wp-config.php
```

So I modified the file `jekyll-export-cli` to 

```
include "../../../wordpress/wp-load.php";
include "../../../wordpress/wp-admin/includes/file.php";
```

Hope you can help me. Regards

**Comment by CaffGeek** [comment]
Same issue here, installed via wordpress plugins, activated, and got 
**Fatal error: Cannot redeclare class Spyc in /.../htdocs/blog/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/Spyc.php on line 57**

**Comment by seraphyn** [comment]
Sign
```PHP Fatal error:  Cannot redeclare class Spyc in /www/htdocs/got/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/Spyc.php on line 57
Fatal error: Cannot redeclare class Spyc in /www/htdocs/got/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/Spyc.php on line 57```

**Comment by benbalter** [comment]
Are you using PHP >= 5.3? https://github.com/benbalter/wordpress-to-jekyll-exporter#a-note-

**Comment by ilessing** [comment]
I'm having a similar issue.  I get the error without doing any jekyll-exporter operation.  I get it as soon as I try to invoke the wordpress cli like this:
`$ wp
Fatal error: Cannot redeclare class Spyc in /home/myuser/documentroot/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/Spyc.php on line 57
`

I'm running php 5.4.42 on Dreamhost
`
$ php --version
PHP 5.4.42 (cli) (built: Jun 16 2015 00:23:52) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
`

**Comment by benbalter** [comment]
What other plugins do you have installed? Is it possible one of them relies on Spyc?

**Comment by BetaLeaf** [comment]
@benbalter Just your own exporter mate. I'm getting the same error on a Windows 10 machine.

**Comment by dancrumb** [comment]
I also see this:

```sh
$ find /home/REDACTED/public_html/wp-content -type f -print0 | xargs -0 grep "class Spyc"
/home/REDACTED/public_html/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/Spyc.php:class Spyc {
/home/REDACTED/public_html/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/php4/spyc.php4:class Spyc {
```

So, the only declarations of that class are yours....

**Comment by dancrumb** [comment]
I wrapped the `Spyc` declaration in a `if(!class_exists)` and now I'm seeing the `cli\render()` error...
