### ISSUE TITLE
Fatal error - undefined function Alchemy/Zippy

### ISSUE THREAD

**Issue by benbrignell** [benbalter/wordpress-to-jekyll-exporter#55]
I've tried again since the update and am getting the following:

```Fatal error: Call to undefined function Alchemy\Zippy\mb_strtolower() in /home/…/public_html/blog/wp-content/plugins/wordpress-to-jekyll-exporter-master/vendor/alchemy/zippy/src/Alchemy/Zippy/Zippy.php on line 189```

I'm on Wordpress 4.1.1

**Comment by benbalter** [comment]
I believe https://github.com/benbalter/wordpress-to-jekyll-exporter/releases/tag/2.0.1 should have fixed this.

**Comment by benbrignell** [comment]
I've updated to the version above but I'm getting exactly the same error - any ideas @benbalter ?
