### ISSUE TITLE
fatal error when activating plugin

### ISSUE THREAD

**Issue by grudelsud** [benbalter/wordpress-to-jekyll-exporter#56]
hey

just so you know, plugin is giving me an error the moment I try to activate it. I'm with WP 4.0.1 on godaddy (not sure what php they have)

this is what I have

```
Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /home/content/i/a/m/iamadroid/html/tom/wp-content/plugins/jekyll-exporter/jekyll-exporter.php on line 27
```

**Comment by argp** [comment]
Same.

**Comment by benbalter** [comment]
I added [a note to the readme](https://github.com/benbalter/wordpress-to-jekyll-exporter#a-note-), you'll need to select PHP 5.3 or later in your host's control panel and then things should work.
