### ISSUE TITLE
Issue: Browser cannot find export.php

### ISSUE THREAD

**Issue by bluelena69** [benbalter/wordpress-to-jekyll-exporter#57]
I am trying to use your plugin to export my current site to Jekyll. I first installed via the Wordpress install in my admin (via the plugins site). I encountered the following issue, deactivated and deleted the plugin and then did a manual download, upload and install. I am getting the same issue either way. Any ideas? I am sure it has to do with some quirk with my hosting at ipage.

Output error====
File not found
Firefox can't find the file at http://johnyux.com/wp-admin/export.php?type=jekyll.

**Comment by benbalter** [comment]
I suspect something's up with your WordPress installation. [That's a core WordPress file](https://github.com/WordPress/WordPress/blob/master/wp-admin/export.php)

**Comment by jcortell** [comment]
I get the same error.
I have two WP installations, in the same server. In one, the export worked perfectly. In the other, same error as reported.
