### ISSUE TITLE
Custom post types don't export

### ISSUE THREAD

**Issue by thinkhuman** [benbalter/wordpress-to-jekyll-exporter#60]
Unless I misunderstand something, custom post types (set up via a custom post type plugin) don't get included in an export, no matter what I try. Is this missing, or am I missing it? Custom post types are very common.

**Comment by benbalter** [comment]
Right now it's limited to Posts and Pages, but if you modify [this line](https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/master/jekyll-exporter.php#L93), you should be able to include custom post types.

**Comment by thinkhuman** [comment]
Ben, modify it how? is it just adding an argument 'custom' after 'post', 'page'? Unsure of how your plugin works on this.

**Comment by benbalter** [comment]
>  is it just adding an argument 'custom' after 'post', 'page'?

It'd be the name of your custom post type, but yes, that's exactly it.

**Comment by szyam** [comment]
works perfect!

**Comment by benbalter** [comment]
Support for custom post types has been added via https://github.com/benbalter/wordpress-to-jekyll-exporter/commit/6ebf0bba65de6449375e98012ef11a5956ff79f6, and will be available in the next release.
