### ISSUE TITLE
Export seems not to respect parent pages

### ISSUE THREAD

**Issue by dcernst** [benbalter/wordpress-to-jekyll-exporter#62]
One of my Wordpress blogs is 100% pages and 0% posts.  Most pages have parent pages and many of these subpages have the same name.  For example:

http://teaching.danaernst.com/mat220s15/syllabus/
http://teaching.danaernst.com/mat220s15/syllabus/

However, only one page named syllabus was exported.

**Comment by sumdog** [comment]
Can confirm. I've encountered this same issue. I only had a few pages, so I just added the permalinks manually.

**Comment by benbalter** [comment]
This is fixed via dd81648, and will be available in the next version.

**Comment by dcernst** [comment]
Thanks!
