### ISSUE TITLE
PHP Error When Using PHP v5.3.29

### ISSUE THREAD

**Issue by pbattisson** [benbalter/wordpress-to-jekyll-exporter#63]
I have installed this as a plugin to export to Jekyll and I am getting the following error:

Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The Process class relies on proc_open, which is not available on your PHP installation.' in /home/neus/public_html/wp-content/plugins/jekyll-exporter/vendor/symfony/process/Symfony/Component/Process/Process.php:148 Stack trace: #0 /home/neus/public_html/wp-content/plugins/jekyll-exporter/vendor/symfony/process/Symfony/Component/Process/ProcessBuilder.php(279): Symfony\Component\Process\Process->__construct(''/usr/bin/unzip...', NULL, Array, NULL, NULL, Array) #1 /home/neus/public_html/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/VersionProbe/ZipVersionProbe.php(72): Symfony\Component\Process\ProcessBuilder->getProcess() #2 /home/neus/public_html/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/AbstractAdapter.php(142): Alchemy\Zippy\Adapter\VersionProbe\ZipVersionProbe->getStatus() #3 /home/neus/public_html/wp-content/plugins/jekyll-exporter/vendor/alche in /home/neus/public_html/wp-content/plugins/jekyll-exporter/vendor/symfony/process/Symfony/Component/Process/Process.php on line 148

The installation docs recommend PHP >5.3 - is this still the case?

**Comment by benbalter** [comment]
> 'The Process class relies on proc_open, which is not available on your PHP installation.'

The framework requires a PHP component which is disabled on your machine. Are you able to enable `proc_open`?

**Comment by rossmounce** [comment]
I have run into this issue as well.

My default php.ini file has these functions disabled for security:

```
; Following disabled_functions are commonly used by malicious scripts, enable at your own risk
disable_functions = "dl,passthru,proc_open,proc_close,allow_url_fopen"
```

Which of these, including proc_open do I need to temporarily enable?
