### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by evanjmg** [benbalter/wordpress-to-jekyll-exporter#64]
T_STRING, expecting T_CONSTANT_ENCAPSED_STRING - Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING  - on line 32 jekyll-exporter.php

**Comment by benbalter** [comment]
Please see [the note on supported PHP versions](https://github.com/benbalter/wordpress-to-jekyll-exporter#a-note-)
