### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by pooran** [benbalter/wordpress-to-jekyll-exporter#65]
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in D:\HostingSpaces\************\wwwroot\wp-content\plugins\wordpress-to-jekyll-exporter-master\jekyll-exporter.php on line 32
PHP Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in D:\HostingSpaces\************\wwwroot\wp-content\plugins\wordpress-to-jekyll-exporter-master\jekyll-exporter.php on line 32

**Comment by benbalter** [comment]
Please see https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/master/readme.md#a-note-.
