### ISSUE TITLE
Markdown converter places all links at the end of the document which can break excepts 

### ISSUE THREAD

**Issue by sumdog** [benbalter/wordpress-to-jekyll-exporter#66]
I noticed the export plugin likes to place all the links at the bottom and then reference them using the markdown bracket syntax:

    [Some link][1] and some text 
    ....rest of the blog post....
    [1]: http://example.org

I can appreciate it trying t consolidate links, but this totally breaks using {{ post.excerpt }} since the links aren't available in the except. I'm going to look into this, but I thought I'd post an issue here first. 

I think the solution needs to be an option to inline the links instead of separating them.

**Comment by sumdog** [comment]
Just an update, the markdown converter supports having them inline by setting ```const LINK_IN_PARAGRAPH = 2;``` as a constructor argument. Quick and dirty you can hack this

    $converter = new Markdownify\ConverterExtra(2);

...into the plugin. If I get time I'll try to make it a setting in the plugin and do a pull request.

**Comment by benbalter** [comment]
Fixed via https://github.com/benbalter/wordpress-to-jekyll-exporter/commit/88fe49bc1dbac829f202fd88ff013aa12e4fafb7. Thanks for the suggestion @sumdog!
