### ISSUE TITLE
Reference Links Don't Work Because of a Single Blank

### ISSUE THREAD

**Issue by sigul** [benbalter/wordpress-to-jekyll-exporter#67]
Hi, 
[reference links][1] don't work. this happens because there's a blank space at the beginning of the line.

Example:
{{ highlight raw }}
this is a [reference link[[1] in my post

 [1]: this is the link
{{ endhighligh }}

note the blank space between the hedge of the ilne and the first [.

[1]: like this one

**Comment by benbalter** [comment]
I believe this will be fixed by upgraded to the latest version of https://github.com/Elephant418/Markdownify when the plugin is released next.
