### ISSUE TITLE
Unable to Execute /usr/bin/zip

### ISSUE THREAD

**Issue by PeteMichaud** [benbalter/wordpress-to-jekyll-exporter#68]
Running Wordpress 4.3.1 on PHP 5.3, when I try to export I'm getting this error:

Fatal error: Uncaught exception 'Alchemy\Zippy\Exception\RuntimeException' with message 'Unable to execute the following command '/usr/bin/zip' '-r' '/tmp/wp-jekyll.zip' './' {output: }' in /home/opini/petermichaud.com/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/ZipAdapter.php:80 Stack trace: #0 /home/opini/petermichaud.com/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Alchemy/Zippy/Adapter/AbstractAdapter.php(56): Alchemy\Zippy\Adapter\ZipAdapter->doCreate('/tmp/wp-jekyll....', Array, true) #1 /home/opini/petermichaud.com/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Alchemy/Zippy/Zippy.php(61): Alchemy\Zippy\Adapter\AbstractAdapter->create('/tmp/wp-jekyll....', Array, true) #2 /home/opini/petermichaud.com/wp-content/plugins/jekyll-exporter/jekyll-exporter.php(301): Alchemy\Zippy\Zippy->create('/tmp/wp-jekyll....', Array, true) #3 /home/opini/petermichaud.com/wp-content/plugins/jekyll-exporter/jekyll-exporter.php(226): Jekyll_Export->zip() #4 /home/opini/p in /home/opini/petermichaud.com/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Alchemy/Zippy/Zippy.php on line 63

**Comment by benbalter** [comment]
@PeteMichaud What host are you using?

**Comment by matthewgraybosch** [comment]
I encountered the same problem on Dreamhost. Here's my result.


Fatal error: Uncaught exception 'Alchemy\Zippy\Exception\RuntimeException' with message 'Unable to execute the following command '/usr/bin/zip' '-r' '/tmp/wp-jekyll.zip' './' {output: }' in /home/wp_4w9idv/matthewgraybosch.com/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Adapter/ZipAdapter.php:80 Stack trace: #0 /home/wp_4w9idv/matthewgraybosch.com/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Adapter/AbstractAdapter.php(56): Alchemy\Zippy\Adapter\ZipAdapter->doCreate('/tmp/wp-jekyll....', Array, true) #1 /home/wp_4w9idv/matthewgraybosch.com/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Zippy.php(68): Alchemy\Zippy\Adapter\AbstractAdapter->create('/tmp/wp-jekyll....', Array, true) #2 /home/wp_4w9idv/matthewgraybosch.com/wp-content/plugins/jekyll-exporter/jekyll-exporter.php(310): Alchemy\Zippy\Zippy->create('/tmp/wp-jekyll....', Array, true) #3 /home/wp_4w9idv/matthewgraybosch.com/wp-content/plugins/jekyll-exporter/jekyll-exporter.php(235): Jekyll_Export->zip() #4 /home/wp_4w9idv in /home/wp_4w9idv/matthewgraybosch.com/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Zippy.php on line 70

**Comment by dylan-k** [comment]
I am also getting errors with zippy on Dreamhost
