### ISSUE TITLE
Lots of warnings, can't copy

### ISSUE THREAD

**Issue by InsidiousMind** [benbalter/wordpress-to-jekyll-exporter#69]
I have around 1,392 lines of this warning:
    <br />
      <b>Warning</b>:  copy(/tmp/wp-jekyll-882eeccfbda5cb780ef7d0d6a09439d4/http://liquidthink.net/wp-content/uploads/2014/02/Artificial-Intelligence-Eye-750x400.jpg): failed to open stream: No such file or directory in <b>/homepages/2/d424055434/htdocs/LiquidThink/wp-admin/includes/class-wp-filesystem-direct.php</b> on line <b>231</b><br />
<br />

I'm running PHP 5.6 with latest WP version. Not sure why this is happening :-(

EDIT: I believe it's because it's trying for the http version, and i have the image on https. Don't know if thats it, though. Where can I change it to copy the https version? 

Though I kinda doubt that's the issue

EDIT: Stupid me never changed http to https in the Wordpress general settings.

But getting the symfony error #49

**Comment by alxmjo** [comment]
I'm having the same problem (the one at the top of your post). Did you ever find a solution?

**Comment by benbalter** [comment]
> EDIT: Stupid me never changed http to https in the Wordpress general settings.
