### ISSUE TITLE
Output ZIP Seems to be corrupt

### ISSUE THREAD

**Issue by junderhill** [benbalter/wordpress-to-jekyll-exporter#70]
The zip file produced always seems to be corrupt. I've tried opening it in multiple apps (windows extractor, winrar) also unzip on OSX. 

On windows it states its corrupt. Under OSX it extracts to a cpgz file which extracts to a zip, this then repeats.

**Comment by alxmjo** [comment]
Usually when I run the plugin it doesn't even get to the step of downloading a zip file, but when it does, this same thing happens for me.

**Comment by benbalter** [comment]
I'm not able to reproduce the issue, but I believe version 2.1.1 could resolve this by updating the various Zip-related dependencies.

**Comment by escaton** [comment]
This seems that something went wrong in wordpress core, and you got an HTML with error description. Just try to run `php jekyll-export-cli.php` without adding `> tmp.zip` and you wil see the html output. Or try to open result zip in any text editor.

**Comment by BetaLeaf** [comment]
@escaton I tried doing what you said. Unforunately, it returns nothing. [screenshot](http://i.imgur.com/ocw8KTS.jpg)

**Comment by escaton** [comment]
Hm, it returns empty string, does your wordpress site works fine?

**Comment by BetaLeaf** [comment]
Ofc. Https://betaleaf.net

On Wed, Feb 3, 2016, 6:22 PM Egor Blinov <notifications@github.com> wrote:

> Hm, it returns empty string, does your wordpress site works fine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/70#issuecomment-179526204>
> .
>
-- 
Jeff Savage
www.betaleaf.net

===

Is your computer feeling sluggish or infected with a virus? I offer
affordable virus removal and support. Visit my website at
www.betaleaf.net/virus-removal to learn more.

**Comment by littlecho** [comment]
Hi there, i have the same issue while I was trying to export my whole wordpress blog. Here is an alternative way for anyone who wants to get your tarball without errors:
1. Editor "jekyll-exporter.php" with your favorite editor(e.g. vim).
2. goto line 251, or find the code "$this->cleanup()"; 
3. comment out "$this->cleanup();"

After all, first you have to execute the export script by going to admin web portal and click "Export to jekyll" and wait for several seconds to have everything created for you. You can navigate to /tmp folder and find folder with prefix name 'wp-jekyll-' and a file called wp-jekyll.zip. Just download 'wp-jekyll.zip' by scp or other programs, you can get a correct archive file for further processing then.

**Comment by BetaLeaf** [comment]
I'm still getting 500 Errors

**Comment by gianpaj** [comment]
I had the same issue using the plugin from the admin interface. The zip file is corrupted.
Using the `wp` cli outputs this error:
```
$ wp jekyll-export
PHP Fatal error:  Cannot redeclare class Spyc in /var/www/html/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/Spyc.php on line 57
Fatal error: Cannot redeclare class Spyc in /var/www/html/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/Spyc.php on line 57
```
The only thing that worked is:
```
$ cd wp-content/plugins/jekyll-exporter/
$ php jekyll-export-cli.php > ~/export.zip
```

And the ignoring this error when extracting the zip file by using the command line:
```
$ unzip export.zip
Archive:  export.zip
warning [export.zip]:  135 extra bytes at beginning or within zipfile
  (attempting to process anyway)
   creating: thedgitupway/
  inflating: _config.yml
...
```

Look at this output:
```
$ php jekyll-export-cli.php
<link  type="text/css" media="all" rel="stylesheet"  href="http://www.dgitup.com/wp-content/plugins/accordions/themes/flat/style.css" >PK
thedgitupway/UT	I1�VJ1�Vux
                          ��P��~H6J[g
...
```

**Comment by gianpaj** [comment]
Not sure if the zip file contains everything or is actually corrupted.
When running `jekyll`, I'm getting these warnings and the site is basically empty:
```
$ jekyll serve
Configuration file: /Users/user/Desktop/jekyll/_config.yml
            Source: /Users/user/Desktop/jekyll
       Destination: /Users/user/Desktop/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'post' requested in _posts/2013-11-05-post-without-image.md does not exist.
     Build Warning: Layout 'post' requested in _posts/2015-07-15-about-us-1.md does not exist.
     Build Warning: Layout 'page' requested in front-page.md does not exist.
...
```

**Comment by XhmikosR** [comment]
Yeah, I'm hitting the same issue too; the ZIP is created, download starts, and the ZIP file fails to download.

**Comment by carolineorlando** [comment]
+1 for the same problem.

Running from wp-cli throws this error: 

`Fatal error: Cannot redeclare class Spyc in /Users/XXX/Documents/code/vvv/vagrant-local/www/wordpress-default/wp-content/plugins/jekyll-exporter/vendor/mustangostang/spyc/Spyc.php on line 57`

Manually firing the export generates a corrupt zip file (zip -> cpgz on a mac). Tested with Twenty Sixteen theme, all other plugins deactivated.

**Comment by carolineorlando** [comment]
Update for those having the same issue - deactivating and reactivating the plugin seemed to clear the issue.

**Comment by craigdrayton** [comment]
I'm getting the same problem + deactivating and reactivating didn't resolve it for me.

**Comment by ain** [comment]
Reproduced as well. Writes a 0-byte zip file, nothing in there. 

At the very least it should throw up with a sensible error message if it fails. Currently it appears to just pack nothing.

**Comment by enguyen** [comment]
Also reproduced: Running from console (`php jekyll-export-cli.php > ~/export.zip`) results in a 0-byte file. Running PHP 5.5, Wordpress 4.6 (just upgraded, but I don't think that's the issue if others are having the same one from back in July.)

**Comment by enguyen** [comment]
Additional note: I did some rudimentary logging to stdout in `jekyll-exporter.php`, and it seems like the callback that's set up in the initial `__construct` method is registered, but never invoked.

I should also note that activating the plugin actually causes my entire WP instance (4.6, as noted above) to fail silently. Hence me trying to use the CLI. But that fact above could make my issue different from others' here.

**Comment by maartenzam** [comment]
Same issue: generates empty zip file (WP 4.6.1).

**Comment by LewisLebentz** [comment]
Issue is still occurring for me, ZIP downloads then unzips into a .cpgz, then back to a ZIP and repeat...

**Comment by Purus** [comment]
I can confirm that this issue is still happening.

**Comment by jeremyzilar** [comment]
I got around it simply by unzipping the zip file via terminal.  `unzip -a jekyll-export.zip`. 
For some reason this works where as unzipping via the finder does not.

This was only an issue for me when I was trying to export the larger site I have (locally). But the workaround above should work. I created a new test site with just a few posts in it (locally) and does not seem to be happening there.

**Comment by jeremyzilar** [comment]
Correction — it works for me sometimes :)

I am currently getting this error when trying to unzip via the terminal ```End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.```

**Comment by staringispolite** [comment]
I get the same error. In wordpress, I get warnings, which prevents the auto-download, since the browser doesn't realize the output is supposed to be a .zip. If I downloaded the output anyway, and manually deleted the ASCII warnings in front, I would get the same warning @jeremyzilar reports above.

If I tried the CLI script, I got `Call to undefined function add_action()`

The workaround from @littlecho to track down the /tmp/wp-jekyll-### directory worked, but I hope a fix is coming out soon. Tracking this down was pretty arduous

**Comment by jeremyzilar** [comment]
@staringispolite — I did realize that I needed to have my log file open when running this. That way, I can watch for errors as it runs. Found that that errors in the code usually result in me not being able to unzip the zip file.

In short, it is working for me now, when I am working with it.

**Comment by jeremyzilar** [comment]
Thank you @benbalter for writing this. It was a great starting point for combing through and exporting what has been a very complicated and messy WP Install.
