### ISSUE TITLE
Activation failure (v2.1.0): fatal error

### ISSUE THREAD

**Issue by patridge** [benbalter/wordpress-to-jekyll-exporter#71]
I've installed the WordPress to Jekyll Exporter via the built-in WordPress plugin system. It ran successfully with a previous version, but when I updated to v2.1.0 and tried to activate it, I get the following error (only path edited):

> Plugin could not be activated because it triggered a fatal error.
> Warning: require_once(/[path-to-site]/public_html/wp-content/plugins/jekyll-exporter/lib/cli.php): failed to open stream: No such file or directory in /[path-to-site]/public_html/wp-content/plugins/jekyll-exporter/jekyll-exporter.php on line 30

It looks like the /lib folder and its contents are not being installed at all when installing the plugin through the admin plugin system. Here is a quick shot of what the plugin directory looks like after doing so.

<img width="151" alt="screen shot 2016-01-11 at 07 49 07" src="https://cloud.githubusercontent.com/assets/713665/12236577/e505558e-b837-11e5-9116-b2460fd17217.png">

I've tried completely uninstalling it and reinstalling it, with no luck.

I'm planning to manually copy things over to give it a shot that way, but I wanted to bring it up in case it was just a symptom of some sort of deeper issue with that plugin installer system.

**Comment by benbalter** [comment]
@patridge thanks for reporting this. Seems the push to wordpress.org didn't work as planned. Released a new version [v2.1.1](https://github.com/benbalter/wordpress-to-jekyll-exporter/releases/tag/v2.1.1), which should contain the missing dependencies on wordpress.org.  You can also download the zip from here and upload if that still fails.

**Comment by patridge** [comment]
@benbalter Thank you for fixing it. I can confirm that the new version worked perfected for this [previously affected] site.
