### ISSUE TITLE
Silently fails when memory limit exceeded

### ISSUE THREAD

**Issue by brian-nelson** [benbalter/wordpress-to-jekyll-exporter#74]
On a blog website that I have had for several years with lots of pictures, the plugin fails and a empty file will be downloaded.

I looked in the apache logs and found an exception of 

```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 246677504 bytes) in ...
```

After trying several different memory settings I found that upping the WP_MAX_MEMORY_LIMIT setting in the default-constants.php file in the wp-includes folder.  I set it to 1024M then ran the export again and it was successful.

I am not sure if the plugin can display something to warn users of this state or not.

Either way the issue is resolved for me, just creating the issue it in case someone else runs into this problem.

Thanks for building the plugin

**Comment by tsmithco** [comment]
I'm having the same issue - but this didn't resolve it for me.

`PHP Fatal Error: Out of Memory (Allocated 1122238464) (Tried to allocate 1075158327 bytes) in /var/www/site/wp-includes/functions.php on line 3553`

**Comment by brian-nelson** [comment]
Have you tried maybe a higher limit like 2048M.  My file was around 268megs, but looks like you are exporting over 1075 megs.  But it really depends on the amount of physical memory you have available on the box.

**Comment by tsmithco** [comment]
I've got 1.75 GB in the server.  I changed the max setting to 1224, got the exact same error (and values, which are under 1224MB. :(  What's interesting is that the allocated value is higher then what it tried to allocate.
