### ISSUE TITLE
PHP Fatal error:  Allowed memory size exhausted 

### ISSUE THREAD

**Issue by akshayeshenoi** [benbalter/wordpress-to-jekyll-exporter#81]
Using the latest version from git-master, php version (5.5.29) that comes bundled with bitnami (/opt/bitnami/php/bin/php), and wp-cli version (0.23.0)(/usr/local/bin/wp).

When I try to run the plugin through CLI, I get the following error:

```
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 1716689425 bytes) in /opt/bitnami/apps/wordpress/htdocs/wp-includes/functions.php on line 3549
PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0
```

I have also set the maximum memory limit for php, along with the WP_MAX_MEMORY_LIMIT, to 2048M. It did not help.

Also tried running the application through the WP-CLI, and I get this:

```
PHP Fatal error:  Cannot redeclare class Spyc in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wordpress-to-jekyll-exporter-master/vendor/mustangostang/spyc/Spyc.php on line 57
Fatal error: Cannot redeclare class Spyc in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wordpress-to-jekyll-exporter-master/vendor/mustangostang/spyc/Spyc.php on line 57

```

Running wp in general causes that error. I need to disable the plugin to make it work again.

**Comment by ogbaoghene** [comment]
@akshayeshenoi seeing the same issue on my WP installation. How are you making do?
