### ISSUE TITLE
Question about dev status

### ISSUE THREAD

**Issue by COLABORATI** [benbalter/wordpress-to-jekyll-exporter#82]
Are you still interested in workig on this plugin or is this project abandoned?
Please tell us if you need somebody else to maintain this, thank you!

**Comment by benbalter** [comment]
I'm still interested in seeing this project succeed, as I think there's a need for it, but don't have use for it myself. If you'd like to contribute, @COLABORATI, I'd be more than glad to review and merge pull requests, with the goal of eventually maintaining the project, if you'd like.

**Comment by COLABORATI** [comment]
Ben, when you have no time to maintain it, it would be great if you would like to remove the code from the wordpress plugin site, as it is only stealing precious lifetime of people in the current disfunctional state (and maybe breaks stuff).

Please re-publish if everything is fine and when there is a new maintainer. Please do not just publish code to some place and the let it bitrot - code is like a baby, you have to take care for it as long as it lives. 

Thank you very much for your attention!
