### ISSUE TITLE
Breaks Wordpress 4.6.x

### ISSUE THREAD

**Issue by akatasonov** [benbalter/wordpress-to-jekyll-exporter#83]
Wordpress 4.6 started using Requests library - the same version that this plugin is using. However the version of the library shipped with the plugin is much older than the one used by Wordpress internally. The result is below

`PHP Fatal error:  Call to undefined method Requests_Response::is_redirect() in /var/www/katasonov.com/httpdocs/wp-includes/class-requests.php on line 685`

**Comment by jpswade** [comment]
`[error] [client 79.64.183.240] PHP Fatal error:  Call to undefined method Requests_Response::is_redirect() in /public_html/.../wp-includes/class-requests.php on line 685`

**Comment by joacimmelin** [comment]
Same here. Running 4.6.1.

**Comment by benbalter** [comment]
Is anyone interested in putting a pull request together to address this?

**Comment by akatasonov** [comment]
Removing Requests from composer.json/composer.lock and updating composer dependencies makes it work again, when used from Wordpress admin (haven't tested the command line option).

**Comment by benbalter** [comment]
@akatasonov would you like to submit a pull request with those changes?

**Comment by benbalter** [comment]
This should be fixed in [v2.2.0](https://github.com/benbalter/wordpress-to-jekyll-exporter/releases/tag/v2.2.0)
