### ISSUE TITLE
Include Post Format

### ISSUE THREAD

**Issue by dylan-k** [benbalter/wordpress-to-jekyll-exporter#87]
I'm working with a site that still has [post formats](https://codex.wordpress.org/Post_Formats) in use. It would be great to be able to include that data within the exported YAML headers for the posts. Is there a way to do this?

**Comment by benbalter** [comment]
[It should do that](https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/dcf947c3eee91839f255140f79875948eae51396/jekyll-exporter.php#L225-L226). Is it not?

**Comment by dylan-k** [comment]
It does. Sorry to have overlooked that.
