### ISSUE TITLE
Directly converting from wordpress exported xml file

### ISSUE THREAD

**Issue by akshayranganath** [benbalter/wordpress-to-jekyll-exporter#89]
Is there an option within the CLI to convert blog posts from an exported XML file?

I am using the free public instance of wordpress (wordpress.com). In here, I can add custom plugins. I can export the posts as an XML file. I was looking for a tool that can consume this XML and spit out the corresponding blog posts.

**Comment by benbalter** [comment]
Take a look at http://import.jekyllrb.com/docs/wordpressdotcom/.

**Comment by akshayranganath** [comment]
Thank you! This helps.
