### ISSUE TITLE
The Process class relies on proc_open, which is not available on your PHP installation

### ISSUE THREAD

**Issue by johnpitchko** [benbalter/wordpress-to-jekyll-exporter#91]
Installed version 2.2.0 of this plugin on my hosted WordPress install version 4.7.5.

When I click on Tools > Export to Jekyll, I receive the following error:
`Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The Process class relies on proc_open, which is not available on your PHP installation.'`

**Comment by fuzzy76** [comment]
FWIW, I'm pretty sure this is because you host has explicitly disabled proc_open(). Probably not much to do about it.
