### ISSUE TITLE
Runs but doesn't seem to do anything

### ISSUE THREAD

**Issue by taddmencer** [benbalter/wordpress-to-jekyll-exporter#92]
I'm trying to run this on a simple shared website (Dreamhost). I go to Tools > Export and it runs.

I wait .. and wait .. but it never actually completes the export. I don't get any errors, just a constant spinning circle in the tab and a blank white page.

**Comment by taddmencer** [comment]
![image](https://cloud.githubusercontent.com/assets/1148597/26515340/eeda0334-4247-11e7-9065-3105ba4f5602.png)

**Comment by Joshfindit** [comment]
It seems I'm also affected by this.
Mine may be different because I get a loading and eventually a crash when accessing the settings for the plugin.

The following leads me to think it's similar:

```
php jekyll-export-cli.php > jekyll-export.zip
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-includes/class-wp-list-util.php on line 153
```

**Comment by mgrowan** [comment]
Same happening here:
Warning: Invalid argument supplied for foreach() in D:\home\site\wwwroot\wp-includes\class-wp-list-util.php on line 153

**Comment by benbalter** [comment]
It looks like this is warning when `wp_list_pluck` is being run on what it things is an array of terms, but really isn't, without a full backtrace or enough information to reproduce the warning, it's hard to tell.

That said, it should just be a warning, meaning the fix on master to buffer the output may resolve the issue.

**Comment by mgrowan** [comment]
I just commented out the call, wasn't that important to me. It then failed in zipping, but I grab the unzip files from the temp directory, so I got enough out. Thanks for the tool, was a great help.

**Comment by fuzzy76** [comment]
I'm also hitting this... :-/

**Comment by fuzzy76** [comment]
get_the_terms() can return false. You forgot to check. Pull-request submitted. :)
