### ISSUE TITLE
Zippy\mb_strtolower() error with a self hosted WP and PHP 7.1.5

### ISSUE THREAD

**Issue by junihh** [benbalter/wordpress-to-jekyll-exporter#93]
I get this error when I try to export with command line:

    /public/wp-content/plugins/jekyll-exporter# php jekyll-export-cli.php
    PHP Fatal error:  Uncaught Error: Call to undefined function Alchemy\Zippy\mb_strtolower() in /public/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Zippy.php:196
    Stack trace:
    #0 /public/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Zippy.php(109): Alchemy\Zippy\Zippy->sanitizeExtension('zip')
    #1 /public/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Zippy.php(173): Alchemy\Zippy\Zippy->addStrategy(Object(Alchemy\Zippy\FileStrategy\ZipFileStrategy))
    #2 /public/wp-content/plugins/jekyll-exporter/jekyll-exporter.php(414): Alchemy\Zippy\Zippy::load()
    #3 /public/wp-content/plugins/jekyll-exporter/jekyll-exporter.php(335): Jekyll_Export->zip()
    #4 /public/wp-content/plugins/jekyll-exporter/jekyll-export-cli.php(28): Jekyll_Export->export()
    #5 {main}
      thrown in /public/wp-content/plugins/jekyll-exporter/vendor/alchemy/zippy/src/Zippy.php on line 196

**Comment by neldredge** [comment]
You have to install the mbstring extension.  See http://php.net/manual/en/mbstring.installation.php

**Comment by junihh** [comment]
Sorry for my late answer. Thanks for your help, I'll try that.
