### ISSUE TITLE
failed to open stream: Invalid argument

### ISSUE THREAD

**Issue by ohadschn** [benbalter/wordpress-to-jekyll-exporter#95]
I'm getting these warnings for seemingly all my uploads:
```Warning: copy(D:\local\Temp/wp-jekyll-4fb2fbff67f749711ccd626e2536c2f0/http://www.ohadsoft.com/wp-content/uploads/2010/01/everything-1024x476.png): failed to open stream: Invalid argument in D:\home\site\wwwroot\wp-admin\includes\class-wp-filesystem-direct.php on line 257 ```

### Environment
Azure Web App (IIS on Windows)
PHP 5.6
[Project Nami](http://projectnami.org/) (WordPress on MS SQL Server) 4.8.1 
Twenty Sixteen Theme 1.3
Site: https://www.ohadsoft.com

**Comment by ohadschn** [comment]
This was due to a [bug in wp_upload_dir](https://core.trac.wordpress.org/ticket/25449) - it doesn't support HTTPS whereas `get_site_url` does support it so the replace operation failed and resulted in illegal Windows file name. Here is the fix (in ):

```php
function convert_uploads() 
{

	$upload_dir = wp_upload_dir();
	$source = $upload_dir['basedir'];
	$siteUrl = trailingslashit( set_url_scheme(get_site_url(), 'http') );
	$baseUrl = set_url_scheme($upload_dir['baseurl'], 'http');
	$dest = $this->dir . str_replace($siteUrl , '',  $baseUrl);
	$this->copy_recursive( $source, $dest );
}
```

**Comment by ohadschn** [comment]
Once that's fixed there is another issue, that stems from the same root cause as https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/96. The fix is easier here though, because we can simply replace `$temp_dir` (again in [jekyll-exporter.php](https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/6e36c09fab4356a64971dfe71fbc6c148588619a/jekyll-exporter.php#L314)) when running in an Azure Web App:

```php
function init_temp_dir() 
{
	global $wp_filesystem;

	add_filter( 'filesystem_method', array( &$this, 'filesystem_method_filter' ) );

	WP_Filesystem();

	// when on Azure Web App use d:/home/temp/ to avoid weird default temp folder behavior
	$temp_dir = (getenv("WEBSITE_SITE_NAME") !== false) ? 'd:/home/temp/' : get_temp_dir();

	$this->dir = $temp_dir . 'wp-jekyll-' . md5( time() ) . '/';
	$this->zip = $temp_dir . 'wp-jekyll.zip';
	$wp_filesystem->mkdir( $this->dir );
	$wp_filesystem->mkdir( $this->dir . '_posts/' );
	$wp_filesystem->mkdir( $this->dir . 'wp-content/' );
}
```

**Comment by benbalter** [comment]
@ohadschn This is great. Would you be able to submit a Pull Request with these changes so that others can benefit?

**Comment by benbalter** [comment]
@ohadschn was excited to get these fixes implemented for other users:

> Here is the fix

Implemented via https://github.com/benbalter/wordpress-to-jekyll-exporter/commit/a1d9b7b95cb5648ac1365b1604ebe8f7dda53fa8

> Once that's fixed there is another issue,

Implemented via https://github.com/benbalter/wordpress-to-jekyll-exporter/commit/399e03a4a9dd79cbe2afab544f7a6d8e60e6e245

**Comment by ohadschn** [comment]
Thank you, this is great! 

Unfortunately I'm afraid this is a bug:
https://github.com/benbalter/wordpress-to-jekyll-exporter/blob/59b411423c6d4fae74fbc1f7c5d48f5bc164f170/jekyll-exporter.php#L324

It turns out that [you can't call `realpath` on a path that doesn't exist](https://secure.php.net/manual/en/function.realpath.php), which would typically be the case with `d:/home/temp` the first time the plugin is used (I made that path up, it's not a "real" temp folder). Here is my suggested fix (tested): 

```php
// when on Azure Web App use %HOME%\temp\ to avoid weird default temp folder behavior
// for more information see https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system
$temp_dir = (getenv( 'WEBSITE_SITE_NAME' ) !== false) ? (getenv('HOME') . DIRECTORY_SEPARATOR . 'temp') : get_temp_dir();
$wp_filesystem->mkdir($temp_dir);
$temp_dir = realpath( $temp_dir ) . DIRECTORY_SEPARATOR;
```

**Comment by benbalter** [comment]
Nice. Thanks for that. Updated via e07d61a.
