### ISSUE TITLE
Could not open wp-admin/export.php?type=jekyll

### ISSUE THREAD

**Issue by bluezd** [benbalter/wordpress-to-jekyll-exporter#98]
I use wordpress 4.8.1 and download jekyll-exporter from `https://wordpress.org/plugins/jekyll-exporter/`, after activate it successfully in wordpress I am not able to run it with the error as $subject.

Any workarounds for resolving this problem ?

**Comment by bluezd** [comment]
Any comments here ?

**Comment by benbalter** [comment]
Does the problem persist with version 2.2.2?

**Comment by bluezd** [comment]
@benbalter I tried with version 2.2.2 and issue persist.

**Comment by bluezd** [comment]
I think it is a common and hot issue, can you take a look at it and come up with a solution or patch ? Thanks !

**Comment by benbalter** [comment]
@bluezd without more information, I'm afraid I am not able to offer advice or a solution. Does it continue if you disable all other plugins? Can you provide a screenshot of the error page? What version of PHP are you running?

**Comment by ohadschn** [comment]
@bluezd  also how/where is your WordPress blog hosted?

**Comment by bluezd** [comment]
Here is the screen shot regarding the error [https://imagebin.ca/v/3YcAxZMUkqyg](https://imagebin.ca/v/3YcAxZMUkqyg)

My wordpress hosts in budgetvm VPS

**Comment by bluezd** [comment]
And the php version is PHP 5.5.14

**Comment by ohadschn** [comment]
@bluezd what OS (include the version)? 

Also, I suggest you [turn on debugging](https://codex.wordpress.org/Debugging_in_WordPress#Example_wp-config.php_for_Debugging) and install a [debug plugin](https://wordpress.org/plugins/wp-log-viewer/). Then paste the warnings/errors it emits here.

**Comment by bluezd** [comment]
The OS is Fedora 20.

When I enable the debug mode, I get the following debug message:
`Class 'ZipArchive' not found
 Type: PHP Fatal error Line: 435
 File: /var/www/wordpress/wp-content/plugins/jekyll-exporter/jekyll-exporter.php`

I install php-pecl-zip package by executing `yum install php-pecl-zip` 
Then I restart the httpd and re-did the whole process finally there is a file pop-up for downloading named jekyll-export.zip. I think it works for me. Thank you all !

**Comment by ohadschn** [comment]
Great. BTW In Ubuntu that would be:
`sudo apt-get install php7.0-zip`

@benbalter looks like a side effect of removing Zippy. Can you "include" `ZipArchive` in the plugin somehow? If not, maybe bring it back and only use `ZipArchive` on Azure?

**Comment by Giorat** [comment]
I get this error too.

**Comment by ohadschn** [comment]
@Giorat we'll need more information in order to be able to help you. See the last few comments for the info we need and debugging suggestions.
